version: '3.3'
services:
  nuxt:
    build:
      context: .
    image: my_portfolio_nuxt_dev
    container_name: my_portfolio_nuxt_dev
    command: npm run dev
    volumes:
    - .:/app
    - node_modules:/app/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"
volumes:
  node_modules: